### ISSUE TITLE
ModelFormSetMixin/BaseInlineFormSetMixin assumes the model attribute is set

### ISSUE THREAD

**Issue by hvdklauw** [AndrewIngram/django-extra-views#10]
They both use self.model which does not need to be set at all for the other cases.

I suggest adding a get_model method to the BaseFormSetMixin which tried to get the model from self.model and otherwise get's it from the self.get_queryset().model

Thus removing the need to define a queryset and a model.

**Comment by jonashaag** [comment]
Please provide an example so that I can better understand your use case.
