### ISSUE TITLE
Save request.user to an django extra view

### ISSUE THREAD

**Issue by bobhsr** [AndrewIngram/django-extra-views#107]
The example is from Django-Extra-Views. Seems to be working as the example states.

Throws errors if added request.user

https://django-extra-views.readthedocs.org/en/latest/views.html

	class OrderCreateView(CreateWithInlinesView):
	    model = Order
	    inlines = [ItemsInline, TagsInline]

	    def get_success_url(self):
	        return self.object.get_absolute_url()

The following have been tried. They do not work.

	def form_valid(self, form):
        # self.object = form.save()
        form.instance.owner = self.request.user
        form.save()
        return super(OrderCreateView, self).form_valid(form)

    throws error:
     IntegrityError at /add/
	 null value in column "owner_id" violates not-null constraint

Also tried adding it form.save

	def save(self,  commit=True):
        instance = super(OrderCreateView, self).save(commit=False)
        instance.owner = self.request.user
        instance.save()

    throws 
    'OrderForm' object has no attribute 'request'

**Comment by berkerpeksag** [comment]
Hey @bobhsr, I've solved the same problem with following code:

```py
class DocumentFormSetCreateView(CreateWithInlinesView):
    # your normal settings

    def forms_valid(self, form, inlines):
        self.object = form.save()
        revision = inlines[0].save(commit=False)[0]  # we just have one item
        revision.creator = self.request.user
        revision.save()
        return HttpResponseRedirect(self.get_success_url())
```

So, you'll need to override the `forms_valid`method instead of `form_valid`.

**Comment by bobhsr** [comment]
If anybody is having the issue, I was able to get it to work by adding the following to the View.


    def forms_valid(self, form, inlines):
        form.instance.owner = self.request.user
        return super(CreateView, self).forms_valid(form, inlines)

**Comment by jonashaag** [comment]
Is this an error in the documentation?

**Comment by AndrewIngram** [comment]
I don't think so, the docs don't cover this, but the solutions to the issue seem to follow best practices (at least they were last time I used Django), so I don't think anything needs to be done.
