### ISSUE TITLE
Support for modifying a django-crispy-forms form in get and post of Inlines Views

### ISSUE THREAD

**Issue by idahogray** [AndrewIngram/django-extra-views#112]
I am working with django-crispy-forms and django-extra-views and I need to modify a form before returning the result using crispy-forms dynamics layouts (http://django-crispy-forms.readthedocs.org/en/latest/dynamic_layouts.html).

Would there be interest in adding this functionality into django-extra-views? I am thinking a method call in ProcessFormWithInlinesView get and post methods.

I wanted to see if there was interest before I starting working on it.

**Comment by jonashaag** [comment]
Could you make a sketch of the changes you'd like to make? Why can't you simply make use of `get_form` and `get_form_class`?

**Comment by idahogray** [comment]
I think you are right that I should use get_form. I will close this issue. Thanks for the quick response.
