### ISSUE TITLE
Bug in formsets.BaseFormSetMixin.initial

### ISSUE THREAD

**Issue by sergei-maertens** [AndrewIngram/django-extra-views#123]
I just ran into this issue for a project, currently BaseFormSetMixin is defined like this:

```
class BaseFormSetMixin(object):
    """
    Base class for constructing a FormSet within a view
    """

    initial = []
    form_class = None
    formset_class = None
    success_url = None
    extra = 2
    max_num = None
    can_order = False
    can_delete = False
    prefix = None

   #  ... left of for brevity
```

The problem is the default value for `initial`. Lists and dictonaries should never be used in class definitions or as default arguments for function definitions, because they are shared between all instances and they are mutable.

The offending code in this case is:

```
    def get_initial(self):
        initial = super(CateringInline, self).get_initial()
        picked_articles = self.object.catering_articles.all()
        for article in self._get_articles():
            if article in picked_articles:
                continue
            initial.append({
                'article': article,
                'amount': 0,
            })
        return initial
```

In this case, `BaseFormSetMixin.initial` is ever-increasing, leading to weird bugs.

**Comment by jonashaag** [comment]
This should be solved by using `initial = None` and checking for `None` in the places we need it as a list.

**Comment by auvipy** [comment]
this can be closed as well.
