### ISSUE TITLE
Problem with forms_valid in the ProcessMultiFormView

### ISSUE THREAD

**Issue by robertomorati** [AndrewIngram/django-extra-views#126]
Hi,

In the older version of extra_views the method post worked fine for me.  Now, I have a problem in the def post(self, request, *args, **kwargs).... because the follow fragment of code has changed.

In the last version:

```
if valid:
    handler = 'valid_%s' % label
    if hasattr(self, handler):
        getattr(self, handler)(valid_forms)
    **return self.forms_valid() # has changed here**
```

In the older version:

```
if valid:
    handler = 'valid_%s' % label
    if hasattr(self, handler):
        getattr(self, handler)(valid_forms)
   ** return self.forms_valid(valid_forms) # pass the valid_forms**
````

I need recover the valid forms. Any idea to solve this?

Thanks,

**Comment by jonashaag** [comment]
Hi, I'm sorry to say that multi is not supported anymore (indeed, it isn't even part of the code base anymore at this point).

**Comment by robertomorati** [comment]
Hi @jonashaag ,

Why the support was removed? 

Thanks,

**Comment by AndrewIngram** [comment]
Multi was never officially included (it was never documented). It was an experiment to find a pattern that could work, but I was never happy with the result.
