### ISSUE TITLE
Provide a new release?

### ISSUE THREAD

**Issue by vdboor** [AndrewIngram/django-extra-views#129]
The last 0.7.1 release was 1 year ago (2015-06-15). Many useful fixes have been added, for Django 1.9 compatibility and even security fixes (#114). Could you please release the current state was a new release, e.g. 0.8?

**Comment by jonashaag** [comment]
There's a 1.0.0 milestone that I'd like to achieve before making a release.

**Comment by vdboor** [comment]
Ah I see. Glad to know the project is still alive and well!

If it won't be possible to release a 1.0 soon, I'd be happy to have a 0.8 release that contains some of the current fixes. For now I'll use a github release in the `requirements.txt` file that uses the latest commit.

**Comment by jonashaag** [comment]
I'm fine with doing a 0.8 release. Does someone volunteer to update the change log accordingly? It's as simple as summarising the Git logs.

**Comment by vdboor** [comment]
@jonashaag You can find the new changelog in my pull request #131

**Comment by jonashaag** [comment]
Here we go!

**Comment by vdboor** [comment]
Wonderful!!
