### ISSUE TITLE
Django 1.10/1.11 release

### ISSUE THREAD

**Issue by AndrewIngram** [AndrewIngram/django-extra-views#142]
Despite owning the repo, i'm not actively using this library (or Django at the moment), but it looks like we're in need of cutting a release. It seems there are quite a few unreleased changes in master? I'm also receiving personal emails about it, so there's clearly a lot of interest.

@jonashaag is there anything in particular that's holding up a 1.10 (and ideally 1.11) release? If there's anything you need help with let me know, it'll take me a while to get back up to speed but i'll do what I can.

**Comment by jonashaag** [comment]
There's a ton of important unfixed issues here: https://github.com/AndrewIngram/django-extra-views/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0

But yeah we could release the current master.

**Comment by mmarcos** [comment]
@jonashaag that would be really great, pinning a dependency on a github branch can be problematic, github returns http 429 too many connections if more than a couple of downloads are being done there. So we are in a bit of a pickle now regarding jango-extra-views and django 1.10

**Comment by jonashaag** [comment]
Done! Please check out version 0.9.0 on PyPi

**Comment by mmarcos** [comment]
Fantastic! Thanks!

**Comment by AndrewIngram** [comment]
Thanks @jonashaag!
