### ISSUE TITLE
Documentation build at readthedocs.io is failing

### ISSUE THREAD

**Issue by sdolemelipone** [AndrewIngram/django-extra-views#175]
https://readthedocs.org/projects/django-extra-views/builds/5606569/

Ideas on what we can do to get it buliding again...looks like the last build attempt was in June 2017... @jonashaag do you have access at readthedocs? Could you take a look or grant me some login details so I can try and get it working? Thanks.

**Comment by jonashaag** [comment]
@AndrewIngram can you give me and @sdolemelipone RTD admin permissions

**Comment by AndrewIngram** [comment]
@jonashaag I've added you, but need RTD usernames for everyone else

**Comment by sdolemelipone** [comment]
Cheers, my username on RTD is sdolemelipone.

**Comment by AndrewIngram** [comment]
Done!

**Comment by sdolemelipone** [comment]
:+1: Thanks, I have access. Will work on getting them building successfully.

**Comment by sdolemelipone** [comment]
Bingo! Just needed to stop the virtualenv looking for a `requirements.txt` file and switch the build to occur on Python 3.
