### ISSUE TITLE
universal wheel is configured, but not built

### ISSUE THREAD

**Issue by therefromhere** [AndrewIngram/django-extra-views#182]
Hi, this it seems like recent builds of this package have been built with the tar.gz only, not the wheel as well, though setup.cfg is set up to create a universal wheel.  It seems like the most recent wheel build was version 0.7.1.

All that needs to happen is passing the bdist_wheel arg to setup.py - ie

```
python setup.py sdist bdist_wheel upload
```
instead of 

```
python setup.py sdist upload
```
see https://pythonwheels.com/

**Comment by jonashaag** [comment]
I’ll try to remember that next time, thank you!

**Comment by sdolemelipone** [comment]
Is this something which is configured via Pypi.org?

**Comment by therefromhere** [comment]
@sdolemelipone no i don't think so, you need to upload built wheels to pypi.
