### ISSUE TITLE
ModelFormSetView doesn't save changes

### ISSUE THREAD

**Issue by faulander** [AndrewIngram/django-extra-views#208]
I have two problems, i have a flat table with settings in my db, structure is:
setting: char
value: char

First Problem: It shows an empty field combination at the end:
![image](https://user-images.githubusercontent.com/38588197/71720172-10455880-2e21-11ea-855b-0cc45908c5ba.png)

Second problem:
It doesn't save the data, no error, no redirect to the success page, nothing.

my views.py:
```
class UpdateSettings(ModelFormSetView):
    model = Settings
    fields = ['setting', 'value']
    template_name = 'settings.html'
    success_url = '/shows'
```

my settings.html:
```
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ formset.management_form }}
        {% for form in formset %}
            <div class="row">
                <div class="col-6">            
                    {{ form.setting|as_crispy_field }}
                </div>
                <div class="col-6">            
                    {{ form.value|as_crispy_field }}
                </div>
            </div>
        {% endfor %}
        <div class="form-group form-actions">
            <button class="btn btn-success">Change</button>
        </div>
    </form>
{% endblock %}
```

**Comment by jonashaag** [comment]
Maybe the form has errors and you’re not seeing them because you’re not rendering errors in the template

**Comment by sdolemelipone** [comment]
And to answer your first problem, that blank row at the end is how you'd define new rows in your settings table. It's there because `extra=1` is the default value for `django.forms.formsets.formset_factory()`. If you don't want an extra form, set 
```python
class UpdateSettings:
    ...
    factory_kwargs = {'extra': 0}
```
this is in [the docs](https://django-extra-views.readthedocs.io/en/latest/pages/formset-views.html#formset-constructor-and-factory-kwargs).
