### ISSUE TITLE
Add Mechanism To Prevent Form Resubmission

### ISSUE THREAD

**Issue by 9mido** [AndrewIngram/django-extra-views#217]
There should be a way to prevent a form from resubmitting again after a form processes and also double submission when a user clicks submit multiple times during a single form processing instance. A user should be able to set a period of time of how long until an authenticated user / anonymous user can be able to submit the form again. Sort of like a rate limiting / throttling mechanism.

**Comment by jonashaag** [comment]
While this a great suggestion, I’m afraid it is out of scope for the project. Sorry.
