### ISSUE TITLE
No tag for 0.14.0

### ISSUE THREAD

**Issue by jayvdb** [AndrewIngram/django-extra-views#231]
https://github.com/AndrewIngram/django-extra-views/releases/tag/0.13.0 is the latest tag, but https://pypi.org/project/django-extra-views/0.14.0/ was released a bit over a week ago.

**Comment by sdolemelipone** [comment]
Good point! @jonashaag I have drafted a release, can you check it and release?

**Comment by jonashaag** [comment]
Sorry, forgot to push the tags.
