### ISSUE TITLE
Release on pypi

### ISSUE THREAD

**Issue by Azd325** [AndrewIngram/django-extra-views#268]
Hi django-extra-views team, 
is there any chance to release 0.15.0?
That would make it easier to verify if the project works on the stated versions table without crawling through the commits to see if there are any related changes are made to support higher Django/python versions since the release of 0.14.0

That would also release this change https://github.com/AndrewIngram/django-extra-views/pull/237 

Cheers

**Comment by sdolemelipone** [comment]
@jonashaag if I make a patch to add Django 5.1 too, will you perform a release after that?

**Comment by jonashaag** [comment]
@sdolemelipone can I transfer ownership to you please. I'm no longer interested in maintaining

**Comment by sdolemelipone** [comment]
> @sdolemelipone can I transfer ownership to you please. I'm no longer interested in maintaining

Yes of course. If there are any other credentials (I think I have readthedocs access) please send them across.

**Comment by jonashaag** [comment]
Ah, I can't add you to PyPI because I'm not the owner. Please ask @AndrewIngram

**Comment by sdolemelipone** [comment]
@AndrewIngram my account on PyPI is also **sdolemelipone**.

**Comment by sdolemelipone** [comment]
I will also look at resolving the issue with codecov once I have access to the repository secrets...

**Comment by jonashaag** [comment]
sure, release current main?

**Comment by sdolemelipone** [comment]
Yes please :+1:

**Comment by sdolemelipone** [comment]
Do you have access to the secrets for this repository as a "higher level" maintainer? I do not.

**Comment by sdolemelipone** [comment]
> sure, release current main?

Andrew added me and I've successfully released the package on PyPI. If we don't have access to repository secrets I'll look into an alternative for Codecov.

Thanks so much for your help and advice with maintaining this package over the last few years. :pray:

**Comment by Azd325** [comment]
Thank you, guys.
