### ISSUE TITLE
Multiview: change prefix container to set instead of list.

### ISSUE THREAD

**Issue by hansonkd** [AndrewIngram/django-extra-views#47]
In `ProcessMultiFormView`:

Instead of having prefixes be a list for this section:

        posted_prefixes = []

        # First we detect which prefixes were POSTed
        for prefix in self.get_form_definitions().keys():
            for field in self.request.POST:
                if field.startswith(prefix):
                    posted_prefixes.append(prefix)
                    break

        # Now we iterated over the groups until we find one that matches the POSTed prefixes
        for label, prefixes in self.get_groups().iteritems():
            if label == 'all' or list(prefixes) == posted_prefixes:

Wouldn't it make more sense to have prefixes be a set? I was debugging for an hour trying to figure out why things wouldn't work, when I figured out that the computed `posted_prefixes` were something like ["left_form", "right_form"] and my group's prefixes (that it was comparing it to) were ["right_form", "left_form"]. Obviously these didn't match and I kept getting a 404 error. Using a set would solve this issue and simplify problems in the future.

**Comment by jonashaag** [comment]
Multi will go away with the next release.
