### ISSUE TITLE
Use of ImageFields in inlineformsets

### ISSUE THREAD

**Issue by stephendwolff** [AndrewIngram/django-extra-views#49]
Hi there, 

Thanks for an excellent set of views - they're very handy.

However - i don't seem to be able to get new image files to get uploaded when the forms are saved with the UpdateWithInlinesView. I suspect the contents of request.FILES isn't being bound to the model? My form definitely has an enctype="multipart/form-data" attribute.

Do you have any suggestions?

Many thanks,

Stephen

**Comment by jonashaag** [comment]
Is this still an issue for you?

**Comment by stephendwolff** [comment]
I think we found another way round it - so, no, not an issue for me. Not sure if it's still an issue with django-extra-views or not.

**Comment by jonashaag** [comment]
OK, closing, though this may still be an issue.
