### ISSUE TITLE
Prefetch related for Create/UpdateWithInlinesView

### ISSUE THREAD

**Issue by palm86** [AndrewIngram/django-extra-views#61]
Could someone point me in the direction for how to implement prefetch_related with inline formset views? I have tried to manually override querysets, but these seem to get ignored. Am I missing something? I have a model with lots of inlines and loading the page takes very long depending on the size of the model. My other views that do much more intensive querying are almost instantaneous because of prefetch_related and select_related.

**Comment by svengt** [comment]
Did you ever get an answer to this? I'm having the same problem.
