### ISSUE TITLE
extra_views/multi.py need a documentation

### ISSUE THREAD

**Issue by luzfcb** [AndrewIngram/django-extra-views#66]
Hello @AndrewIngram, no documentation was created for "multi" module because it is not usable or lack of available time to create it?
A minimal documentation for this module would be great.
I'm a little lost on the correct way to use it

nice project, thanks.

**Comment by jonashaag** [comment]
Multi will go away with the next release.

**Comment by luzfcb** [comment]
`extra_views/multi.py` has removed in https://github.com/AndrewIngram/django-extra-views/commit/f7e6f89947200d54a5dfdea7dcd509c1b639f649
