### ISSUE TITLE
docs for the mixins in the main sphinx docs

### ISSUE THREAD

**Issue by henning** [AndrewIngram/django-extra-views#73]
I was just looking for the searchable list mixin docs, but was surprised not even find that listet on the read the docs page - so I first thought it was pretty outdated as the date says also 2013 as the year, but it seems there just is not doc of the mixins in the sphinx docs, only a bit in the readme... maybe at least that bit should be mentioned, so people looking into the docs at least are informed that the mixins _exist_ :)

**Comment by sdolemelipone** [comment]
Fixed by #178 .
