### ISSUE TITLE
ModelFormSetView does not support 1.6 kwargs

### ISSUE THREAD

**Issue by screendriver** [AndrewIngram/django-extra-views#83]
In Django 1.6 they [introduced](https://docs.djangoproject.com/en/1.6/topics/forms/modelforms/#specifying-widgets-to-use-in-the-form-with-widgets) new kwargs that can be passed to modelformset_factory(). Like _widgets_ und _localized_fields_.
Would it be possible to add this fields to the ModelFormSetView class? At the moment I am not experienced enough in Django / django-extra-views to make a pull request :worried:

**Comment by auvipy** [comment]
probably this one is also fixed?
