### ISSUE TITLE
InlineFormSet -  Foreign Key -  Exclude

### ISSUE THREAD

**Issue by osygeek** [AndrewIngram/django-extra-views#87]
Hi,

I'm working on CreateWithInlinesView, and I need to exclude/hide the foreign key attribute  common between my model and inline_model form. I'm stuck with it, no proper solution still able to find. Here is the Code:

class AuthInline(InlineFormSet):
    model = Authentication
    extra = 3
    can_delete = False
    max_num = 3
    fk_name = ('i_client')
    exclude = ('i_client')
    
class ClientTariffBetterCreateView(CreateWithInlinesView):  
    model = ClientTariff
    inlines = [AuthInline]
    template_name = 'tariffs/client_tariff_create.html'
    success_url = '../'

**Comment by nikolas** [comment]
This code worked for me to exclude a `user` field:

```py
class RemindersInlineFormSet(InlineFormSet):
    model = Reminder
    exclude = ['user']
```

**Comment by jonashaag** [comment]
@osygeek was using a parenthesized expression `('i_client')` rather than a tuple `('i_client',)`, not the trailing comma. You may thank the Python language for not having static type checking.
