### ISSUE TITLE
Redirect to model's get_absolute_url in ModelFormSetMixin get_success_url

### ISSUE THREAD

**Issue by palmeida** [AndrewIngram/django-extra-views#92]
I think it would be nice to mimic Django's UpdateView and CreateView behavior of redirecting to the model's get_absolute_url in get_success_url. ModelFormSetMixin uses FormSetMixin's behavior of redirecting to success_url, if it's set, and if not to self.request.get_full_path(). It's not "wrong", and it's easy to bypass, either by providing get_success_url or redirecting manually, but it surprised me and forces me to do it differently from the other views. This is how Django does it in ModelFormMixin:

``` python
 def get_success_url(self):
    """
    Returns the supplied URL.
    """
    if self.success_url:
        url = self.success_url % self.object.__dict__
    else:
        try:
            url = self.object.get_absolute_url()
        except AttributeError:
            raise ImproperlyConfigured(
                "No URL to redirect to.  Either provide a url or define"
                " a get_absolute_url method on the Model.")
    return url
```

**Comment by sdolemelipone** [comment]
Fixed in #183
