### ISSUE TITLE
Ordering InlineFormSetView's via the queryset

### ISSUE THREAD

**Issue by aidanlister** [AndrewIngram/django-extra-views#94]
I'd like to do something like this:

```python
class ServiceContractInlineUpdateView(InlineFormSetView):
    model = Property
    inline_model = ServiceContract
    form_class = ServiceContractInlineForm

    def get_queryset(self):
        qs = super(ServiceContractInlineUpdateView, self).get_queryset()
        return qs.order_by('service__name')
```

But it doesn't seem to work. get_queryset is called by the ordering of the forms is not affected.

**Comment by riv2q** [comment]
try this:

    class ServiceContractInlineUpdateView(InlineFormSetView):
        model = Property
        inline_model = ServiceContract
        form_class = ServiceContractInlineForm

        def construct_formset(self):
            formset = super(ServiceContractInlineUpdateView, self).construct_formset()
            formset.queryset = formset.queryset.qs.order_by('service__name')
            return formset

**Comment by aidanlister** [comment]
Yeah neat that works, thanks.
