### ISSUE TITLE
Find someone to take over ownership of this project

### ISSUE THREAD

**Issue by AndrewIngram** [AndrewIngram/django-extra-views#96]
As is probably clear from the number of open issues and pull requests, I'm not really paying much attention to this project. The reason is a combination of not really working with formsets (or even Django views) much anymore, and a lack of free time outside of work to commit to the project.

So I'm looking for someone who is interested in taking over ownership of the project. It could be trialled by me adding the person as a contributor, and letting them look at the open issues and pull requests and getting things down to a reasonable number. Ideally this person would already be a moderately active open source contributor, so that we don't end up back in the current situation but under a different owner.

I expect that once the backlog of issues is cleared, most work will just be related to keeping dependencies updated, and adding compatibility with future Django versions.

Anybody interested?

**Comment by halfnibble** [comment]
10.5k downloads/month and no responses. It's a shame.

**Comment by delinhabit** [comment]
I'm happy to take ownership of the project, though I can commit no more than ~4 hours a week for it. If you think that is enough, I'm happy to take it.

**Comment by sergei-maertens** [comment]
I would be willing to contribute, recently I've become a lot more active in the OS environment and starting from september I should get a bit more free time since I'm cutting back on the job.

**Comment by jonashaag** [comment]
bump @AndrewIngram I'm interested too

**Comment by vleong2332** [comment]
I really would like to see this project kept alive by those who has volunteered above,  @AndrewIngram.

**Comment by jonashaag** [comment]
@AndrewIngram bump

**Comment by AndrewIngram** [comment]
Based on Github activity, i've added @jonashaag as a contributor (I may add more). What's your pypi username, so I can add you as a maintainer?

Assuming it goes well, I can add more contributors, or transfer ownership of the repo.

**Comment by jonashaag** [comment]
@AndrewIngram It's jonash

**Comment by jonashaag** [comment]
@AndrewIngram what parts of the code do you think are save for deprecation & removal? I'd like to get rid of unused, unmaintained code. From the commit history it looks to me like `multi.py` should go. How about all these mixins? Are they in use at all and do you think they provide some generic value in their current form?

**Comment by AndrewIngram** [comment]
I think multi should go on the basis that once you're hitting that level of complexity, you should really just be writing your own view code, or handling it within the form itself.

The mixins are a bit more complicated. Essentially someone forked the project just to add them (and added a `-ng` suffix on pypi), people started getting confused about which was the active project. So I merged the fork on, but never got around to cleaning up the code. I'd argue in favour of deprecation, working out if they're actually needed, and moving them to their own repo.

Given Django 1.8 is the most recent LTS, and 1.9 will be released shortly. I'd say aim for a 1.0 release that drops compatibility code for 1.7 and below, and use the opportunity to prune all the stuff that's not needed or supported.

**Comment by jonashaag** [comment]
That's what I thought of too. Maybe we can keep Django 1.6, 1.7 support without much effort.

I'm just not sure how to find out which features are used by people and which aren't. Most of the code even has tests (except for multi)

**Comment by AndrewIngram** [comment]
Just FYI, i've added you as a maintainer on the pypi package
